spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

# Rate Limiter: max 5 votos por segundo por instancia
resilience4j.ratelimiter.instances.voteRateLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.voteRateLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.voteRateLimiter.timeout-duration=0
